#!/usr/bin/env bash
set -euo pipefail

# Generate .env.<world> by pulling values from the deployed CloudFormation
# stack codex-<world>-app. Anything that can't be derived (world title,
# Google secrets that don't live in CFN) is either guessed sensibly or
# prompted for.
#
# Usage:
#   ./scripts/make-env.sh <world> [--force]

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <world> [--force]" >&2
  exit 1
fi

WORLD="$1"
FORCE="${2:-}"
STACK="codex-${WORLD}-app"
REGION="${AWS_REGION:-us-east-1}"
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${REPO_DIR}/.env.${WORLD}"

if [[ -f "$OUT" && "$FORCE" != "--force" ]]; then
  echo "ERROR: $OUT already exists. Pass --force to overwrite." >&2
  exit 1
fi

resource_id() {
  aws cloudformation describe-stack-resource \
    --stack-name "$STACK" \
    --logical-resource-id "$1" \
    --region "$REGION" \
    --query 'StackResourceDetail.PhysicalResourceId' \
    --output text
}

stack_param() {
  aws cloudformation describe-stacks \
    --stack-name "$STACK" \
    --region "$REGION" \
    --query "Stacks[0].Parameters[?ParameterKey=='$1'].ParameterValue | [0]" \
    --output text
}

echo "▶ Looking up stack $STACK..."
aws cloudformation describe-stacks --stack-name "$STACK" --region "$REGION" \
  --query 'Stacks[0].StackStatus' --output text > /dev/null

USER_POOL_ID=$(resource_id CodexUserPool)
USER_POOL_CLIENT_ID=$(resource_id CodexUserPoolClient)
IDENTITY_POOL_ID=$(resource_id CodexIdentityPool)
CLOUDFRONT_ID=$(resource_id CodexCloudFrontDistribution)
FRONTEND_BUCKET=$(resource_id CodexFrontEndBucket)
COGNITO_DOMAIN_PREFIX=$(resource_id CodexUserPoolDomain)
API_DOMAIN=$(stack_param ApiDomainName)

TITLE_DEFAULT="$(echo "${WORLD:0:1}" | tr '[:lower:]' '[:upper:]')${WORLD:1}"
read -r -p "World title [${TITLE_DEFAULT}]: " TITLE
TITLE="${TITLE:-$TITLE_DEFAULT}"

echo "▶ Writing $OUT"
cat > "$OUT" <<EOF
# Generated by scripts/make-env.sh on $(date '+%Y-%m-%d %H:%M:%S')
VITE_WORLD_NAME=${WORLD}
VITE_WORLD_TITLE=${TITLE}

VITE_API_URL=https://${API_DOMAIN}
VITE_AWS_REGION=${REGION}

VITE_COGNITO_USER_POOL_ID=${USER_POOL_ID}
VITE_COGNITO_CLIENT_ID=${USER_POOL_CLIENT_ID}
VITE_COGNITO_IDENTITY_POOL_ID=${IDENTITY_POOL_ID}
VITE_COGNITO_DOMAIN=${COGNITO_DOMAIN_PREFIX}.auth.${REGION}.amazoncognito.com

DEPLOY_BUCKET=${FRONTEND_BUCKET}
DEPLOY_CLOUDFRONT_ID=${CLOUDFRONT_ID}
EOF

echo "✓ Wrote $OUT"
echo ""
echo "Next steps:"
echo "  1. Add 'dev:${WORLD}: vite --mode ${WORLD}' to package.json scripts (if not present)"
echo "  2. Add the Cognito Hosted UI callback to Google OAuth client:"
echo "       https://${COGNITO_DOMAIN_PREFIX}.auth.${REGION}.amazoncognito.com/oauth2/idpresponse"
echo "  3. npm run dev:${WORLD}    # local"
echo "  4. ./deploy.sh ${WORLD}    # production"
